version: '3.8'

services:
  app:
    build: .
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "npm run migration:run && npm run start:dev"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: todo-app
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db_data:
