name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files via scp
      run: scp -o StrictHostKeyChecking=no -r . ec2-user@35.173.221.28:/your-app-directory

    - name: Connect and deploy
      run: ssh -o StrictHostKeyChecking=no ec2-user@35.173.221.28 "
            cd ~/your-app-directory &&
            docker-compose down &&
            docker-compose up -d
        "
