name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.3.0
        with:
          host: 35.173.221.28
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@35.173.221.28 "
            cd ~/Docker-Todo-BE &&
            docker-compose down &&
            docker-compose up
          "
