name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0  # Updated version
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Connect and deploy
      run: ssh -o StrictHostKeyChecking=no ec2-user@35.173.221.28 "
            cd ~/Docker-Todo-BE &&
            docker-compose down &&
            docker-compose up -d
        "
